site_name: Version_Switch

site_url: https://mvishwa27.github.io/version_switch_v/
# site_url: https://www.google.com

# site_url: https://opensource.hcltechsw.com/volt-mx-docs/95/docs/documentation/
# # docs_dir: source
# site_dir: docs/95/docs/documentation

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  custom_dir: theme_overrides

extra:
  version:
    provider: mike
    alias: true
  
plugins:
  - mike:
      canonical_version: latest
      alias_type: redirect







# theme: readthedocs
